<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Abc.Xacml" Version="1.2.1" />
	<PackageReference Include="Firely.Fhir.Packages" Version="5.0.2" />
	<PackageReference Include="Firely.Fhir.Validation.R4" Version="3.1.1" />
	<PackageReference Include="Hl7.Fhir.Base" Version="6.1.1" />
	<PackageReference Include="Hl7.Fhir.R4" Version="6.1.1" />
	<PackageReference Include="Hl7.Fhir.Specification.Data.R4" Version="6.1.1" />
	<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.9" />
	<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.9" />
	<PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.3.9" />
	<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.9" />
	<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.7" />
	<PackageReference Include="Microsoft.IdentityModel.Tokens.Saml" Version="8.17.0" />
	<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.17.0" />
	<PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.7" />
	<PackageReference Include="System.ServiceModel.Http" Version="10.0.652802" />
	<PackageReference Include="System.ServiceModel.Primitives" Version="10.0.652802" />
  </ItemGroup>

</Project>
