<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.10" />
	<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.10" />
	<PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.3.10" />
	<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.10" />
	<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
	<PackageReference Include="Microsoft.IdentityModel.Tokens.Saml" Version="8.19.1" />
	<PackageReference Include="nClam" Version="9.0.0" />
	<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
	<PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.8" />
	<PackageReference Include="System.ServiceModel.Http" Version="10.0.652802" />
	<PackageReference Include="System.ServiceModel.Primitives" Version="10.0.652802" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\XcaXds.Terminology\XcaXds.Terminology.csproj" />
  </ItemGroup>

</Project>
