default:
  tags:
    - 2026-03-standard

include:
  - project: helsepersonell/team-plattform/nhn-ci-template
    file: .gitlab-ci.yml
    ref: "0.19.3"

variables:
  IMAGE_NAME: xcadocumentsource
  HARBOR_REPOSITORY: team-dokumentdeling
  HARBOR_IMAGE_REPOSITORY: $IMAGE_NAME
  # Route Docker base image pulls through GitLab Dependency Proxy in CI builds.
  DOCKER_BUILD_ARGS: "--build-arg UPSTREAM_REGISTRY=${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/mcr.microsoft.com"
  BUILD_ARGS: "--build-arg UPSTREAM_REGISTRY=${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/mcr.microsoft.com"
  # enable kaniko image layer caching for faster builds
  NHN_KANIKO_CACHE_ENABLED: true

build image and push to harbor:
  tags:
    - 2026-03-standard
  variables:
    SRC_FOLDER: "XcaXds.WebService"
    CONTEXT_FOLDER: "."
    NHN_DEFAULT_FILTER_EXTRA_PATH: ".gitlab-ci.yml"
    DOCKERFILE: "Dockerfile"
  extends:
    - .nhn-image-build-and-push-harbor

tag manifest:
  tags:
    - 2026-03-standard
  extends:
    - .manifest-repo-update-singlefile
  variables:
    MANIFEST_REPO_URL: milliways.nhn.no/helsepersonell/team-dokumentdeling/xcads/k8s/xcadocumentstore.git
    SRC_FOLDER: "."
    DEPLOY_ENVIRONMENTS: "test"
    NHN_DEFAULT_FILTER_EXTRA_PATH: ".gitlab-ci.yml"

tag manifest prod:
  tags:
    - 2026-03-standard
  extends:
    - tag manifest
  variables:
    DEPLOY_ENVIRONMENTS: "prod"
  when: manual
  