FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .
RUN dotnet restore XcaXds.Frontend/XcaXds.Frontend.csproj
RUN dotnet publish XcaXds.Frontend/XcaXds.Frontend.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "XcaXds.Frontend.dll"]
