FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .

RUN dotnet restore XcaXds.WebService/XcaXds.WebService.csproj
RUN dotnet publish XcaXds.WebService/XcaXds.WebService.csproj -c Release -o /app

COPY XcaXds.Source/Registry /app/registry
COPY XcaXds.Source/Repository /app/repository

FROM mcr.microsoft.com/dotnet/aspnet:8.0

RUN mkdir /mnt/data/registry
RUN mkdir /mnt/data/repository

WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "XcaXds.WebService.dll"]
