apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: xcadocumentsource-ingress
  namespace: xcads-int-nhn
spec:
  ingressClassName: avi-ingress-class-helsenett
  tls:
    - hosts:
        - xds.pjd.test.nhn.no
  rules:
    - host: xds.pjd.test.nhn.no
      http:
        paths:
          - backend:
              service:
                name: xcadocumentsource
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
---
apiVersion: ako.vmware.com/v1alpha1
kind: HostRule
metadata:
  name: xcadocumentsource-hostrule-helsenett
  namespace: xcads-int-nhn
spec:
  virtualhost:
    fqdn: xds.pjd.test.nhn.no
    analyticsProfile: NHN-System-Analytics-Profile
    analyticsPolicy:
      fullClientLogs:
        enabled: true
        throttle: DISABLED
      logAllHeaders: false
