apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-api"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: {{ .Values.api.image }}
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            {{- range $key, $value := .Values.api.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            - name: registry-volume
              mountPath: /app/registry
            - name: repository-volume
              mountPath: /app/repository
      volumes:
        - name: registry-volume
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-registry"
        - name: repository-volume
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-repository"