apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: osl1-w02-cl01-vsan-storage-policy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repository-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: osl1-w02-cl01-vsan-storage-policy
