{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "frank-sykehus-enk.fullname" . }}
  labels:
    {{- include "frank-sykehus-enk.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  tls:
    - hosts:
        - {{ .Values.ingress.fqdn | quote }}
      secretName: {{ include "frank-sykehus-enk.fullname" . }}-tls
  rules:
    - host: {{ .Values.ingress.fqdn | quote }}
      http:
        paths:
          - path: / 
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "frank-sykehus-enk.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
