apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "registry-pvc"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}

