// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XcaXds.Source.Implementations.Statistics.PostGreSql;

#nullable disable

namespace XcaXds.Source.Migrations.Statistics
{
    [DbContext(typeof(StatisticsDbContext))]
    [Migration("20260901104857_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XcaXds.Source.Models.DatabaseDtos.DbUserAccessEntry", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<string>("AccessBasis")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<DateTime>("AccessTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Action")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("DocumentConfidentialityCodesJson")
                    .HasColumnType("text");

                b.Property<long>("ElapsedTimeMillis")
                    .HasColumnType("bigint");

                b.Property<string>("Endpoint")
                    .HasMaxLength(1024)
                    .HasColumnType("character varying(1024)");

                b.Property<string>("Issuer")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("IssuesJson")
                    .HasColumnType("text");

                b.Property<string>("ResourceIdHash")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<int>("ResponseStatusCode")
                    .HasColumnType("integer");

                b.Property<string>("SessionId")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("SourceHomeCommunityId")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("SourceHostName")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("SourceRepositoryUniqueId")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("SubjectChildOrganizationCode")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("SubjectChildOrganizationCodeSystem")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("SubjectChildOrganizationDisplayName")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("SubjectChildOrganizationName")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("SubjectIdHash")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("SubjectOrganizationCode")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("SubjectOrganizationCodeSystem")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("SubjectOrganizationDisplayName")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("SubjectOrganizationName")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<int>("Success")
                    .HasColumnType("integer");

                b.Property<int?>("UploadedEntries")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("AccessTime");

                b.HasIndex("Action");

                b.HasIndex("SessionId");

                b.ToTable("UserAccessEntries");
            });
#pragma warning restore 612, 618
        }
    }
}
