// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XcaXds.Source.Source.RegistryRepository.SqLite;

#nullable disable

namespace XcaXds.Source.Migrations.Sqlite
{
    [DbContext(typeof(SqliteRegistryDbContext))]
    partial class SqliteRegistryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("XcaXds.Source.Models.DatabaseDtos.DbRegistryObject", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("RegistryObjects", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("DbRegistryObject");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("XcaXds.Source.Models.DatabaseDtos.DbAssociation", b =>
                {
                    b.HasBaseType("XcaXds.Source.Models.DatabaseDtos.DbRegistryObject");

                    b.Property<string>("AS_AssociationType")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("AS_SourceObjectId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("AS_SubmissionSetStatus")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("AS_TargetObjectId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasIndex("AS_SourceObjectId");

                    b.HasIndex("AS_TargetObjectId");

                    b.HasDiscriminator().HasValue("DbAssociation");
                });

            modelBuilder.Entity("XcaXds.Source.Models.DatabaseDtos.DbDocumentEntry", b =>
                {
                    b.HasBaseType("XcaXds.Source.Models.DatabaseDtos.DbRegistryObject");

                    b.Property<string>("DE_AvailabilityStatus")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DE_CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DE_Hash")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DE_HomeCommunityId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DE_LanguageCode")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DE_MimeType")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DE_ObjectType")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DE_RepositoryUniqueId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DE_ServiceStartTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DE_ServiceStopTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DE_Size")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DE_SourcePatientInfoBirthTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DE_SourcePatientInfoFirstName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DE_SourcePatientInfoGender")
                        .HasColumnType("TEXT");

                    b.Property<string>("DE_SourcePatientInfoLastName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DE_SourcePatientInfoPatientId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DE_SourcePatientInfoPatientSystem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DE_Title")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("DE_UniqueId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DE_ClassCode", "XcaXds.Source.Models.DatabaseDtos.DbDocumentEntry.DE_ClassCode#DbCodedValue", b1 =>
                        {
                            b1.Property<string>("Code")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("CodeSystem")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Discriminator")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.HasDiscriminator<string>("Discriminator").HasValue("DbCodedValue");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DE_EventCodeList", "XcaXds.Source.Models.DatabaseDtos.DbDocumentEntry.DE_EventCodeList#DbCodedValue", b1 =>
                        {
                            b1.Property<string>("Code")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("CodeSystem")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Discriminator")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.HasDiscriminator<string>("Discriminator").HasValue("DbCodedValue");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DE_FormatCode", "XcaXds.Source.Models.DatabaseDtos.DbDocumentEntry.DE_FormatCode#DbCodedValue", b1 =>
                        {
                            b1.Property<string>("Code")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("CodeSystem")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Discriminator")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.HasDiscriminator<string>("Discriminator").HasValue("DbCodedValue");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DE_HealthCareFacilityTypeCode", "XcaXds.Source.Models.DatabaseDtos.DbDocumentEntry.DE_HealthCareFacilityTypeCode#DbCodedValue", b1 =>
                        {
                            b1.Property<string>("Code")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("CodeSystem")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Discriminator")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.HasDiscriminator<string>("Discriminator").HasValue("DbCodedValue");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DE_LegalAuthenticator", "XcaXds.Source.Models.DatabaseDtos.DbDocumentEntry.DE_LegalAuthenticator#DbLegalAuthenticator", b1 =>
                        {
                            b1.Property<string>("Discriminator")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("IdSystem")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("LastName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.HasDiscriminator<string>("Discriminator").HasValue("DbLegalAuthenticator");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DE_PracticeSettingCode", "XcaXds.Source.Models.DatabaseDtos.DbDocumentEntry.DE_PracticeSettingCode#DbCodedValue", b1 =>
                        {
                            b1.Property<string>("Code")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("CodeSystem")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Discriminator")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.HasDiscriminator<string>("Discriminator").HasValue("DbCodedValue");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DE_TypeCode", "XcaXds.Source.Models.DatabaseDtos.DbDocumentEntry.DE_TypeCode#DbCodedValue", b1 =>
                        {
                            b1.Property<string>("Code")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("CodeSystem")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Discriminator")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.HasDiscriminator<string>("Discriminator").HasValue("DbCodedValue");
                        });

                    b.HasIndex("DE_HomeCommunityId");

                    b.HasIndex("DE_RepositoryUniqueId");

                    b.HasIndex("DE_UniqueId")
                        .IsUnique();

                    b.HasIndex("DE_SourcePatientInfoPatientId", "DE_SourcePatientInfoPatientSystem");

                    b.HasDiscriminator().HasValue("DbDocumentEntry");
                });

            modelBuilder.Entity("XcaXds.Source.Models.DatabaseDtos.DbSubmissionSet", b =>
                {
                    b.HasBaseType("XcaXds.Source.Models.DatabaseDtos.DbRegistryObject");

                    b.Property<string>("SS_AvailabilityStatus")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SS_HomeCommunityId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SS_SourceId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SS_SubmissionTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("SS_Title")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SS_UniqueId")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("DbSubmissionSet");
                });

            modelBuilder.Entity("XcaXds.Source.Models.DatabaseDtos.DbAssociation", b =>
                {
                    b.HasOne("XcaXds.Source.Models.DatabaseDtos.DbRegistryObject", null)
                        .WithMany()
                        .HasForeignKey("AS_SourceObjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("XcaXds.Source.Models.DatabaseDtos.DbRegistryObject", null)
                        .WithMany()
                        .HasForeignKey("AS_TargetObjectId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("XcaXds.Source.Models.DatabaseDtos.DbDocumentEntry", b =>
                {
                    b.OwnsMany("XcaXds.Source.Models.DatabaseDtos.Types.DbAuthorInfo", "DE_Author", b1 =>
                        {
                            b1.Property<string>("DocumentEntryId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("DepartmentAssigningAuthority")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("DepartmentId")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("DepartmentName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("OrganizationAssigningAuthority")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("OrganizationId")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("OrganizationName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("PersonAssigningAuthority")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("PersonFirstName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("PersonId")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("PersonLastName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("RoleCode")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("RoleCodeSystem")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("RoleDisplayName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("SpecialityCode")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("SpecialityCodeSystem")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("SpecialityDisplayName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.HasKey("DocumentEntryId", "Id");

                            b1.ToTable("DocumentEntry_Authors", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DocumentEntryId");
                        });

                    b.OwnsMany("XcaXds.Source.Models.DatabaseDtos.Types.DbCodedValue", "DE_ConfidentialityCode", b1 =>
                        {
                            b1.Property<string>("DocumentEntryId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Code")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("CodeSystem")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.HasKey("DocumentEntryId", "Id");

                            b1.ToTable("DocumentEntry_ConfidentialityCodes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DocumentEntryId");
                        });

                    b.Navigation("DE_Author");

                    b.Navigation("DE_ConfidentialityCode");
                });

            modelBuilder.Entity("XcaXds.Source.Models.DatabaseDtos.DbSubmissionSet", b =>
                {
                    b.OwnsMany("XcaXds.Source.Models.DatabaseDtos.Types.DbAuthorInfo", "SS_Author", b1 =>
                        {
                            b1.Property<string>("SubmissionSetId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Id")
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("DepartmentAssigningAuthority")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("DepartmentId")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("DepartmentName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("OrganizationAssigningAuthority")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("OrganizationId")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("OrganizationName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("PersonAssigningAuthority")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("PersonFirstName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("PersonId")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("PersonLastName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("RoleCode")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("RoleCodeSystem")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("RoleDisplayName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("SpecialityCode")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("SpecialityCodeSystem")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("SpecialityDisplayName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.HasKey("SubmissionSetId", "Id");

                            b1.ToTable("SubmissionSet_Authors", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SubmissionSetId");
                        });

                    b.Navigation("SS_Author");
                });
#pragma warning restore 612, 618
        }
    }
}
